name: Query Issues Output
on:
  workflow_dispatch:
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: christothes/IssueOutputAction@v1.1
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        searchquery: 'is:open'
        repoOwnerAndName: 'rsymo-org/Query-Issues-Output-test'  
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: 'issueoutput_3005026345'
 #       name: 'my-artifact'
        path: path/to/artifacts

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
