name: "Search and output issues"
on:
  workflow_dispatch:
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/IssueOutputAction@v1.0
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        searchquery: 'is:open'
        repoOwnerAndName: 'rsymo-org/Query-Issues-Output-test'
