name: Query Issues Output
on:
  workflow_dispatch:
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: christothes/IssueOutputAction@v1.1
      id: upload
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        searchquery: 'is:open'
        repoOwnerAndName: 'rsymo-org/Query-Issues-Output-test'  
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: ${{ env.GITHUB_RUN_ID }}
#       name: `issueoutput_${process.env['GITHUB_RUN_ID']}`
 #       name: 'my-artifact'
        path: ${{steps.upload.outputs.issuesDirPath}}
#       path: path/to/artifacts

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}

    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Github Issue Query with JSON attached
        to: rsymo@github.com
        from: GitHub Actions # <user@example.com>
        body: "Only ${{ steps.seats.outputs.remaining }} GitHub seats remaining!"
        # Optional attachments:
        attachments: issueoutput_${{ env.GITHUB_RUN_ID }}.zip,git.diff,./dist/static/*.js
